// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wpf_Plc.Infrastructure;

#nullable disable

namespace Wpf_Plc.Infrastructure.Migrations
{
    [DbContext(typeof(PlcAppContext))]
    partial class PlcAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Wpf_Plc.Domain.Entities.PLCDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaudRate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataBits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddressString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("PlcDevices");
                });

            modelBuilder.Entity("Wpf_Plc.Domain.Entities.PLCModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalogInputsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnalogOutputsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("DigitalInputsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DigitalOutputsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<double>("PowerConsumption")
                        .HasColumnType("REAL");

                    b.Property<int>("PowerSupplyType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsCanBus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsEthernet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsExpansionModules")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRS232")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsRS485")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsUsb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlcModels");
                });

            modelBuilder.Entity("Wpf_Plc.Domain.Entities.PLCProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PLCModelId1")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PLCModelId1");

                    b.ToTable("PlcPrograms");
                });

            modelBuilder.Entity("Wpf_Plc.Domain.Entities.PLCDevice", b =>
                {
                    b.HasOne("Wpf_Plc.Domain.Entities.PLCModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Wpf_Plc.Domain.Entities.PLCProgram", b =>
                {
                    b.HasOne("Wpf_Plc.Domain.Entities.PLCModel", "PLCModel")
                        .WithMany()
                        .HasForeignKey("PLCModelId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PLCModel");
                });
#pragma warning restore 612, 618
        }
    }
}
